---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: rabbitmq
  namespace: work
spec:
  releaseName: rabbitmq
  rollback:
    enable: true
  chart:
    repository: https://charts.bitnami.com/bitnami
    name: rabbitmq
    version: 8.15.3
  values:
    service:
      type: LoadBalancer
    auth:
      username: basic
      password: basic
    ingress:
      enabled: true
      hostname: rabbit.web.bluehairfreak.com
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt-prod
        ingress.kubernetes.io/force-ssl-redirect: "true"
        kubernetes.io/ingress.class: contour
        kubernetes.io/tls-acme: "true"
      tls: true
      certManager: true
