---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: vault
  namespace: kube-system
  annotations:
    fluxcd.io/automated: "true"
    filter.fluxcd.io/server: semver:~1
spec:
  releaseName: vault
  rollback:
    enabled: false
  chart:
    repository: https://helm.releases.hashicorp.com
    version: 0.8.0
    name: vault
  values:
    server:
      image:
        repository: "vault"
        tag: "1.7.3"
        # Overrides the default Image Pull Policy
        pullPolicy: IfNotPresent
      updateStrategyType: "RollingUpdate"
      dataStorage:
        enabled: true
      extraEnvironmentVars:
        GOOGLE_APPLICATION_CREDENTIALS: /vault/userconfig/kms-vault/account.json
      extraVolumes:
      - type: secret
        name: kms-vault
        path: /vault/userconfig
      annotations:
        backup.velero.io/backup-volumes: data
      standalone:
        enabled: "false"
      ha:
        enabled: "true"
        replicas: 3
        raft:
          enabled: true
          setNodeId: true
          config: |
            ui = true
            listener "tcp" {
              tls_disable = 1
              address = "[::]:8200"
              cluster_address = "[::]:8201"
            }
            storage "raft" {
              path = "/vault/data"
            }
            seal "gcpckms" {
              project     = "home-gitops"
              region      = "global"
              key_ring    = "vault-unseal"
              crypto_key  = "vault-key"
            }
    ui:
      enabled: true
      serviceType: "ClusterIP"
