git:
  ssh:
    secretName: flux-git-deploy
helm:
  versions: "v3"
prometheus:
  enabled: true
  serviceMonitor:
    create: true
    interval: 30s
    scrapeTimeout: 10s
    namespace: flux
dashboards:
  enabled: true
