---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: helm-operator
  namespace: flux
  annotations:
    fluxcd.io/automated: "true"
    fluxcd.io/tag.chart.image: semver:~1.2
spec:
  releaseName: helm-operator
  helmVersion: v3
  chart:
    repository: https://charts.fluxcd.io/
    name: helm-operator
    version: 1.2.0
  valuesFrom:
  - externalSourceRef:
      url: https://raw.githubusercontent.com/nctiggy/home-gitops/master/flux/helm-operator/flux-helm-operator-values.yaml
