---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: nzbget
  namespace: media
  annotations:
    fluxcd.io/automated: "false"
    filter.fluxcd.io/chart-image: glob:v21.*
spec:
  releaseName: nzbget
  helmVersion: v3
  rollback:
    enable: true
  chart:
    repository: https://k8s-at-home.com/charts/
    name: nzbget
    version: 10.1.0
  values:
    timezone: "America/Los_Angeles"
    persistence:
      config:
        enabled: true
        existingClaim: nzbget
        skipuninstall: true
      downloads:
        enabled: true
        existingClaim: nfs-share
    podSecurityContext:
      runAsUser: 568
      runAsGroup: 568
      fsGroup: 568
  valueFileSecrets:
  - name: "nzbget-helm-values"
