---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: nzbget
  namespace: media
  annotations:
    fluxcd.io/automated: "true"
    filter.fluxcd.io/chart-image: regex:^(v[0-9]+\.[0-9]+-ls.*)$
spec:
  releaseName: nzbget
  helmVersion: v3
  rollback:
    enable: true
  chart:
    repository: https://billimek.com/billimek-charts/
    name: nzbget
    version: 3.3.2
  values:
    image:
      tag: "v21.1-r2311-ls4"
    timezone: "America/Los_Angeles"
    persistence:
      config:
        existingClaim: nzbget-config
        skipuninstall: true
      downloads:
        existingClaim: nfs-pvc
        skipuninstall: true
