---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nzbget
  namespace: media
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 16Gi
  storageClassName: vxflexos
  volumeMode: Filesystem
