---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: nzbget
  namespace: media
  annotations:
    fluxcd.io/automated: "false"
    filter.fluxcd.io/chart-image: glob:v21.*
spec:
  releaseName: nzbget
  helmVersion: v3
  rollback:
    enable: true
  chart:
    repository: https://k8s-at-home.com/charts/
    name: nzbget
    version: 7.4.0
  values:
    image:
      tag: "version-v21.0"
    timezone: "America/Los_Angeles"
    persistence:
      config:
        enabled: true
        existingClaim: nzbget
        skipuninstall: true
      downloads:
        enabled: true
        existingClaim: nfs-share
    additionalVolumes:
    - name: downloads
      persistentVolumeClaim:
        claimName: nfs-share
    additionalVolumeMounts:
    - name: downloads
      mountPath: /downloads
  valueFileSecrets:
  - name: "nzbget-helm-values"
