---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: nzbget
  namespace: media
  annotations:
    fluxcd.io/automated: "true"
    filter.fluxcd.io/chart-image: regex:^(v[0-9]+\.[0-9]+-r.*)$
spec:
  releaseName: nzbget
  helmVersion: v3
  rollback:
    enable: true
  chart:
    repository: https://k8s-at-home.com/charts/
    name: nzbget
    version: 5.0.1
  values:
    nzbget:
      image:
        tag: "v21.1-r2311-ls9"
      timezone: "America/Los_Angeles"
      persistence:
        config:
          existingClaim: nzbget-config
        downloads:
          existingClaim: nfs-pvc
      ingress:
        annotations:
          cert-manager.io/cluster-issuer: letsencrypt-prod
          ingress.kubernetes.io/force-ssl-redirect: "true"
          kubernetes.io/ingress.class: contour
          kubernetes.io/tls-acme: "true"
        tls:
        - secretName: nzbget
          hosts:
          - downloads.web.bluehairfreak.com
        rules:
        - host: downloads.web.bluehairfreak.com
          http:
            paths:
            - path: /
              pathType: Prefix
