---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: nzbget
  namespace: media
  annotations:
    fluxcd.io/automated: "true"
    filter.fluxcd.io/chart-image: glob:v21.*
spec:
  releaseName: nzbget
  helmVersion: v3
  rollback:
    enable: true
  chart:
    repository: https://k8s-at-home.com/charts/
    name: nzbget
    version: 5.0.1
  values:
    nzbget:
      image:
        tag: "v21.1-r2311-ls9"
      timezone: "America/Los_Angeles"
      persistence:
        config:
          enabled: true
          existingClaim: nzbget
          skipuninstall: true
        downloads:
          enabled: true
          existingClaim: nfs-share
      additionalVolumes:
      - name: downloads
        persistentVolumeClaim:
          claimName: nfs-pvc
      additionalVolumeMounts:
      - name: downloads
        mountPath: /downloads
  valueFileSecrets:
  - name: "nzbget-helm-values"
