---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mc-data-wattles
  namespace: minecraft
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 64Gi
  storageClassName: vxflexos
  volumeMode: Filesystem
---
apiVersion: v1
kind: Service
metadata:
  name: minecraft-wattles
  namespace: minecraft
  annotations:
    metallb.universe.tf/address-pool: frontend
spec:
  selector:
    app: mc-wattles
  ports:
    - protocol: TCP
      port: 25565
      targetPort: 25565
  type: LoadBalancer
  externalTrafficPolicy: Local
  loadBalancerIP: "192.168.0.57"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mc-wattles
  namespace: minecraft
spec:
  selector:
    matchLabels:
      app: mc-wattles
  template:
    metadata:
      labels:
        app: mc-wattles
    spec:
      containers:
      - image: itzg/minecraft-server
        name: mc-wattles
        imagePullPolicy: Always
        env:
          # Use secret in real usage
        - name: EULA
          value: "true"
        - name: TZ
          value: "America/Los_Angeles"
        - name: TYPE
          value: "PAPER"
        - name: FORCE_REDOWNLOAD
          value: "TRUE"
        - name: SERVER_NAME
          value: "Surive"
        - name: OPS
          value: "nctiggy"
        - name: MOTD
          value: "Wattles Minecraft Guide"
        - name: ICON
          value: "https://styles.redditmedia.com/t5_o6oqi/styles/communityIcon_a9ptdumocik11.png?width=256&s=bbdeae8eee6ec937aad324569385b1b56069667f"
        - name: SEED
          value: "-6981104862809678893"
        - name: WORLD
          value: "https://download2331.mediafire.com/bfm1nm4ksqmg/a4yac16frng6qo2/Minecraft+Guide+-+wattles+ep+100.zip"
        - name: ONLINE_MODE
          value: "FALSE"
        - name: VERSION
          value: "1.16.5"
        - name: MEMORY
          value: "8G"
        ports:
        - containerPort: 19132
          name: bedrock
        - containerPort: 25565
          name: java
        readinessProbe:
          exec:
            command:
            - mc-monitor
            - localhost
            - ping
          initialDelaySeconds: 5
          periodSeconds: 5
        livenessProbe:
          exec:
            command:
            - mc-monitor
            - localhost
            - ping
          initialDelaySeconds: 5
          periodSeconds: 5
        volumeMounts:
        - name: mc-data-wattles
          mountPath: /data
      volumes:
      - name: mc-data-wattles
        persistentVolumeClaim:
          claimName: mc-data-wattles
