apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  annotations:
    helm.sh/resource-policy: keep
  name: radarr-config
  namespace: media
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 56Gi
  storageClassName: vxflexos
  volumeMode: Filesystem
  volumeName: k8s-4da34e3573
