---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: k10
  namespace: kasten-io
  annotations:
    fluxcd.io/automated: "false"
    filter.fluxcd.io/chart-image: semver:^1
spec:
  releaseName: k10
  helmVersion: v3
  rollback:
    enable: false
  chart:
    repository: https://charts.kasten.io/
    name: k10
    version: 3.0.6
  values:
    auth:
      basicAuth:
        enabled: true
      secretName: kasten-auth
  valueFileSecrets:
  - name: "kasten-helm-values"
