---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: heimdall
  namespace: media
  annotations:
    fluxcd.io/automated: "false"
    filter.fluxcd.io/chart-image: regex:^(2+\.[0-9]+\.[0-9]+-ls.*)$
spec:
  releaseName: heimdall
  helmVersion: v3
  rollback:
    enable: true
  chart:
    repository: https://k8s-at-home.com/charts/
    name: heimdall
    version: 4.3.0
  values:
    image:
      repository: linuxserver/heimdall
      tag: "version-2.2.2"
    persistence:
      config:
        enabled: true
        existingClaim: "heimdall-config"
        skipuninstall: true
  valueFileSecrets:
  - name: "heimdall-helm-values"
