---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: calibre-web
  namespace: media
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 64Gi
  storageClassName: vxflexos
  volumeMode: Filesystem
