---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: harbor
  namespace: harbor
spec:
  releaseName: harbor
  helmVersion: v3
  rollback:
    enable: true
  chart:
    repository: https://helm.goharbor.io
    name: harbor
    version: 1.4.2
  values:
    externalURL: https://harbor.web.bluehairfreak.com
