---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: harbor
  namespace: harbor
spec:
  releaseName: harbor
  helmVersion: v3
  rollback:
    enable: true
  chart:
    repository: https://helm.goharbor.io
    name: harbor
    version: 1.4.2
  values:
    expose:
      tls:
        enabled: false
      ingerss:
        hosts:
          core: harbor.192.168.0.54.xip.io
          notary: harbor-notary.192.168.0.54.xip.io
    externalURL: http://harbor.192.168.0.54.xip.io
    updateStrategy:
      type: Recreate
