apiVersion: ricoberger.de/v1alpha1
kind: VaultSecret
metadata:
  name: harbor-helm-values
  namespace: harbor
spec:
  keys:
    - values.yaml
  path: secrets/harbor/harbor/harbor-helm-values
  type: Opaque
