apiVersion: ricoberger.de/v1alpha1
kind: VaultSecret
metadata:
  name: grafana-secret
  namespace: monitoring
spec:
  keys:
    - admin-user
    - admin-password
  path: secrets/monitoring/grafana/grafana-secret
  type: Opaque
