---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: grafana
  namespace: monitoring
  annotations:
    fluxcd.io/automated: "false"
    fluxcd.io/tag.chart-image: 'regexp:^(1\.[0-9]+\.[0-9]+)$'
spec:
  releaseName: grafana
  rollback:
    enable: true
  chart:
    name: grafana/grafana
    version: 5.6.10
  values:
    datasources:
      datasources.yaml:
        apiVersion: 1
        datasources:
        - name: influxdb-telegraf
          type: influxdb
          url: http://influxdb:8086
          access: proxy
          isDefault: true
          database: telegraf
          jsonData:
            timeInterval: "10s"
