---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: bitwarden
  namespace: shared-services
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 32Gi
  storageClassName: vxflexos
  volumeMode: Filesystem
