---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: bitwardenrs
  namespace: shared-services
spec:
  releaseName: bitwardenrs
  helmVersion: v3
  rollback:
    enable: true
  chart:
    repository: https://k8s-at-home.com/charts/
    name: bitwardenrs
    version: 1.0.0
  values:
    image:
      tag: "1.17.0-alpine"
    persistence:
      enabled: true
      size: 32Gi
    bitwardenrs:
      signupsAllowed: true
      admin:
        existingSecret:
          enabled: true
          name: "bitwarden-admin"
          tokenKey: "password"
    autoscaling:
      enabled: true
      minReplicas: 1
      maxReplicas: 10
      targetCPUUtilizationPercentage: 80
  valueFileSecrets:
  - name: "bitwarden-helm-values"
