---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: metrics-server
  namespace: kube-system
  annotations:
    fluxcd.io/automated: "true"
    filter.fluxcd.io/server: semver:~0
spec:
  releaseName: metrics-server
  rollback:
    enabled: false
  chart:
    version: 5.5.1
    repository: https://charts.bitnami.com/bitnami
    name: metrics-server
  values:
    extraArgs:
      kubelet-insecure-tls: true
