---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: traefik
  namespace: kube-system
  annotations:
    fluxcd.io/automated: "true"
    filter.fluxcd.io/chart-image: semver:2.2
spec:
  releaseName: traefik
  helmVersion: v3
  rollback:
    enable: true
  chart:
    repository: https://containous.github.io/traefik-helm-chart
    name: traefik
    version: 9.1.1
  values:
    image:
      name: traefik
      tag: 2.2.8
      pullPolicy: IfNotPresent
    deployment:
      initContainers:
        - name: volume-permissions
          image: busybox:1.31.1
          command: ["sh", "-c", "chmod -Rv 600 /data/*"]
          volumeMounts:
            - name: data
              mountPath: /data
    additionalArguments:
      - "--certificatesresolvers.myresolver.acme.httpchallenge.entrypoint=web"
      - "--certificatesresolvers.myresolver.acme.storage=/data/acme.json"
    persistence:
      enabled: true
      size: 8Gi
  valueFileSecrets:
    - name: "traefik-values"
