apiVersion: ricoberger.de/v1alpha1
kind: VaultSecret
metadata:
  name: traefik-sso
  namespace: kube-system
spec:
  keys:
    - clientid
    - clientsecret
    - secret
  path: secrets/kube-system/traefik/traefik-sso
  type: Opaque
