---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: radarr
  namespace: media
  annotations:
    fluxcd.io/automated: "true"
    filter.fluxcd.io/chart-image: semver:^3
spec:
  releaseName: radarr
  helmVersion: v3
  rollback:
    enable: true
  chart:
    repository: https://k8s-at-home.com/charts/
    name: radarr
    version: 8.4.0
  values:
    radarr:
      image:
        tag: "3.0.1.4259-ls90"
      env:
        TZ: "America/Los_Angeles"
      persistence:
        config:
          enabled: true
          existingClaim: radarr
          skipuninstall: true
        media:
          enabled: true
          existingClaim: nfs-share
  valueFileSecrets:
  - name: "radarr-helm-values"
