---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: radarr
  namespace: media
  annotations:
    fluxcd.io/automated: "true"
    filter.fluxcd.io/chart-image: regex:^(3+\.[0-9]+\.[0-9]+\.[0-9]+-ls.*)$
spec:
  releaseName: radarr
  helmVersion: v3
  rollback:
    enable: true
  chart:
    repository: https://k8s-at-home.com/charts/
    name: radarr
    version: 6.0.2
  values:
    radarr:
      image:
        repository: linuxserver/radarr
        tag: "arm32v7-3.0.0.3790-ls27"
      env:
        TZ: "America/Los_Angeles"
      persistence:
        config:
          enabled: true
          skipuninstall: true
        media:
          enabled: true
          existingClaim: nfs-pvc
  valueFileSecrets:
  - name: "radarr-helm-values"
