---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: radarr
  namespace: media
  annotations:
    fluxcd.io/automated: "true"
    filter.fluxcd.io/chart-image: semver:3.0
spec:
  releaseName: radarr
  helmVersion: v3
  rollback:
    enable: true
  chart:
    repository: https://billimek.com/billimek-charts/
    name: radarr
    version: 4.1.3
  values:
    image:
      repository: linuxserver/radarr
      tag: "3.0.0.3641-ls21"
    timezone: "America/Los_Angeles"
    podAnnotations:
      backup.velero.io/backup-volumes: config
    persistence:
      config:
        enabled: true
        skipuninstall: true
        existingClaim: radarr-config
      media:
        enabled: true
        existingClaim: nfs-pvc
        skipuninstall: true
