---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: radarr
  namespace: media
  annotations:
    fluxcd.io/automated: "true"
    filter.fluxcd.io/chart-image: semver:3.0
spec:
  releaseName: radarr
  helmVersion: v3
  rollback:
    enable: true
  chart:
    repository: https://k8s-at-home.com/charts/
    name: radarr
    version: 6.0.2
  values:
    radarr:
      image:
        repository: linuxserver/radarr
        tag: "3.0.0.3775-ls23"
      timezone: "America/Los_Angeles"
      persistence:
        config:
          enabled: true
          skipuninstall: true
        media:
          enabled: true
          existingClaim: nfs-pvc
          skipuninstall: true
      ingress:
        enabled: true
        annotations:
          cert-manager.io/cluster-issuer: letsencrypt-prod
          ingress.kubernetes.io/force-ssl-redirect: "true"
          kubernetes.io/ingress.class: contour
          kubernetes.io/tls-acme: "true"
        tls:
        - secretName: radarr
          hosts:
          - movies.web.bluehairfreak.com
        hosts:
        - host: movies.web.bluehairfreak.com
          paths:
          - path: /
            pathType: Prefix
