apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: radarr-config
  namespace: media
  annotations:
    helm.sh/resource-policy: keep
    meta.helm.sh/release-name: radarr
    meta.helm.sh/release-namespace: media
  labels:
    app.kubernetes.io/instance: radarr
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: radarr
    helm.sh/chart: radarr-4.1.3
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 56Gi
  storageClassName: vxflexos
  volumeMode: Filesystem
  volumeName: k8s-4da34e3573
