---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: radarr
  namespace: media
  annotations:
    fluxcd.io/automated: "false"
    filter.fluxcd.io/chart-image: semver:^3
spec:
  releaseName: radarr
  helmVersion: v3
  rollback:
    enable: true
  chart:
    repository: https://k8s-at-home.com/charts/
    name: radarr
    version: 11.1.0
  values:
    env:
      TZ: "America/Los_Angeles"
    persistence:
      config:
        enabled: true
        existingClaim: radarr
        skipuninstall: true
        accessMode: ReadWriteOnce
      media:
        enabled: true
        existingClaim: nfs-share
  valueFileSecrets:
  - name: "radarr-helm-values"
