apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-pvc
  namespace: media
spec:
  accessModes:
  - ReadWriteMany
  resources:
     requests:
       storage: 16Ti
  storageClassName: nfs-dynamic
  volumeMode: Filesystem
  volumeName: nfs-pv
