---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: sonarr
  namespace: media
  annotations:
    fluxcd.io/automated: "true"
    filter.fluxcd.io/chart-image: semver:^3
spec:
  releaseName: sonarr
  helmVersion: v3
  rollback:
    enable: true
  chart:
    repository: https://k8s-at-home.com/charts/
    name: sonarr
    version: 6.0.2
  values:
    sonarr:
      image:
        tag: "3.0.4.981-ls62"
      env:
        TZ: "America/Los_Angeles"
      persistence:
        config:
          enabled: true
          existingClaim: sonarr
          skipuninstall: true
          size: 8Gi
        media:
          enabled: true
          existingClaim: nfs-pvc
  valueFileSecrets:
  - name: "sonarr-helm-values"
