---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: sonarr
  namespace: media
  annotations:
    fluxcd.io/automated: "true"
    filter.fluxcd.io/chart-image: regex:^(3+\.[0-9]+\.[0-9]+\.[0-9]+-ls.*)$
spec:
  releaseName: sonarr
  helmVersion: v3
  rollback:
    enable: true
  chart:
    repository: https://k8s-at-home.com/charts/
    name: sonarr
    version: 6.0.2
  values:
    sonarr:
      image:
        repository: linuxserver/sonarr
        tag: "arm32v7-2.0.0.5344-ls16"
      timezone: "America/Los_Angeles"
      persistence:
        config:
          enabled: true
          skipuninstall: true
          size: 8Gi
        media:
          enabled: true
          existingClaim: nfs-pvc
  valueFileSecrets:
  - name: "sonarr-helm-values"
