---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: sonarr
  namespace: media
  annotations:
    fluxcd.io/automated: "true"
    filter.fluxcd.io/chart-image: semver:~3.0
spec:
  releaseName: sonarr
  helmVersion: v3
  rollback:
    enable: true
  chart:
    repository: https://billimek.com/billimek-charts/
    name: sonarr
    version: 4.1.3
  values:
    image:
      repository: linuxserver/sonarr
      tag: "3.0.3.913-ls40"
    timezone: "America/Los_Angeles"
    podAnnotations:
      backup.velero.io/backup-volumes: config
    persistence:
      config:
        #        existingClaim: sonarr-config
        skipuninstall: true
      media:
        existingClaim: nfs-pvc
        skipuninstall: true
