apiVersion: ricoberger.de/v1alpha1
kind: VaultSecret
metadata:
  name: sonarr-helm-values
  namespace: media
spec:
  keys:
    - values.yaml
  path: secrets/default/sonarr/sonarr-helm-values
  type: Opaque
