---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: sonarr
  namespace: media
  annotations:
    fluxcd.io/automated: "false"
    filter.fluxcd.io/chart-image: semver:^3.
spec:
  releaseName: sonarr
  helmVersion: v3
  rollback:
    enable: true
  chart:
    repository: https://k8s-at-home.com/charts/
    name: sonarr
    version: 11.1.0
  values:
    env:
      TZ: "America/Los_Angeles"
    persistence:
      config:
        enabled: true
        existingClaim: sonarr
        skipuninstall: true
      media:
        enabled: true
        existingClaim: nfs-share
  valueFileSecrets:
  - name: "sonarr-helm-values"
