---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mc-data-survival
  namespace: minecraft
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 64Gi
  storageClassName: vxflexos
  volumeMode: Filesystem
---
apiVersion: v1
kind: Service
metadata:
  name: minecraft-survival-bedrock
  namespace: minecraft
  annotations:
    metallb.universe.tf/address-pool: frontend
spec:
  selector:
    app: mc-survival
  ports:
    - protocol: UDP
      port: 19132
      targetPort: 19132
  type: LoadBalancer
  externalTrafficPolicy: Local
  loadBalancerIP: "192.168.0.55"
---
apiVersion: v1
kind: Service
metadata:
  name: minecraft-survival
  namespace: minecraft
  annotations:
    metallb.universe.tf/address-pool: frontend
spec:
  selector:
    app: mc-survival
  ports:
    - protocol: TCP
      port: 25565
      targetPort: 25565
  type: LoadBalancer
  externalTrafficPolicy: Local
  loadBalancerIP: "192.168.0.56"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mc-survival
  namespace: minecraft
spec:
  selector:
    matchLabels:
      app: mc-survival
  template:
    metadata:
      labels:
        app: mc-survival
    spec:
      containers:
      - image: itzg/minecraft-server:java16
        name: mc-survival
        imagePullPolicy: Always
        env:
          # Use secret in real usage
        - name: EULA
          value: "true"
        - name: TZ
          value: "America/Los_Angeles"
        - name: TYPE
          value: "PAPER"
        - name: FORCE_REDOWNLOAD
          value: "TRUE"
        - name: SERVER_NAME
          value: "Surive"
        - name: OPS
          value: "nctiggy"
        - name: MOTD
          value: "Little Hope"
        - name: ICON
          value: "https://image.winudf.com/v2/image/Y29tLmNob2NvbGF0ZXN0b25lLmNocmlzdG1hc2dpcmxzX2ljb25fczU0bDRydmg/icon.png?w=170&fakeurl=1"
        - name: SEED
          value: "572779209"
        - name: ONLINE_MODE
          value: "FALSE"
        - name: VERSION
          value: "1.17.1"
        - name: MEMORY
          value: "8G"
        ports:
        - containerPort: 19132
          name: bedrock
        - containerPort: 25565
          name: java
        readinessProbe:
          exec:
            command:
            - mcstatus
            - localhost
            - ping
          initialDelaySeconds: 5
          periodSeconds: 5
        livenessProbe:
          exec:
            command:
            - mcstatus
            - localhost
            - ping
          initialDelaySeconds: 5
          periodSeconds: 5
        volumeMounts:
        - name: mc-data-survival
          mountPath: /data
      volumes:
      - name: mc-data-survival
        persistentVolumeClaim:
          claimName: mc-data-survival
