---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: influxdb
  namespace: monitoring
  annotations:
    fluxcd.io/ignore: "false"
    fluxcd.io/automated: "true"
    fluxcd.io/tag.chart-image: 'regexp:^(1\.[0-9]+\.[0-9]+)$'
spec:
  releaseName: influxdb
  rollback:
    enable: true
  chart:
    repository: https://helm.influxdata.com/
    name: influxdb
    version: 4.8.2
  valuesFrom:
  - externalSourceRef:
      url: https://raw.githubusercontent.com/nctiggy/home-gitops/master/monitoring/influxdb/influxdb-values.yaml
