persistence:
  enabled: true
  size: 128Gi
startupProbe:
  enabled: true
  failureThreshold: 6
  periodSeconds: 5
config:
  opentsdb:
    enabled: true
  graphite:
    enabled: true
podAnnotations:
  backup.velero.io/backup-volumes: influxdb-data
