---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: home-assistant
  namespace: iot
  annotations:
    fluxcd.io/automated: "true"
    filter.fluxcd.io/chart-image: semver:~0.
spec:
  releaseName: home-assistant
  rollback:
    enable: true
  chart:
    repository: https://k8s-at-home.com/charts/
    name: home-assistant
    version: 2.5.2
  values:
    image:
      repository: homeassistant/home-assistant
      tag: 2021.1.4
    persistence:
      enabled: true
      #      existingClaim: home-assistant
    service:
      type: LoadBalancer
      loadBalancerIP: 192.168.0.53
    hostNetwork: true
    probes:
      liveness:
        enabled: false
      readiness:
        enabled: false
    podAnnotations:
      backup.velero.io/backup-volumes: config
    monitoring:
      enabled: false
    postgresql:
      enabled: true
      global:
        postgresql:
          postgresqlUsername: home-assistant
          postgresqlDatabase: home-assistant
      persistence:
        enabled: true
        skipUninstall: true
        #        existingClaim: home-assistant-postgresql
    configurator:
      enabled: true
      ingress:
        enabled: false
  valueFileSecrets:
  - name: "home-assistant-values"
