apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: home-assistant-postgresql
  namespace: iot
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 96Gi
  storageClassName: vxflexos
  volumeMode: Filesystem
