---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: plex
  namespace: media
  annotations:
    fluxcd.io/automated: "true"
    filter.fluxcd.io/chart-image: semver:^1
spec:
  releaseName: plex
  helmVersion: v3
  rollback:
    enable: false
  chart:
    repository: https://k8s-at-home.com/charts/
    name: plex
    version: 2.0.4
  values:
    image:
      tag: "1.20.3.3437-f1f08d65b"
    timezone: "Americas/Los_Angeles"
    allowedNetworks:
    - 127.0.0.1
    - 192.168.0.0/24
      #serviceTCP:
      #  type: LoadBalancer
      #  loadBalancerIP: 192.168.0.52
      #  externalTrafficPolicy: Local
      #serviceUDP:
      #  type: LoadBalancer
    persistence:
      transcode:
        enabled: true
      data:
        enabled: true
        claimName: "nfs-pvc"
      config:
        enabled: true
        claimName: "plex-config"
    certificate:
      pkcsMangler:
        enabled: true
        certificateSecret:
          name: "plex"
          keyName: "tls.key"
          crtName: "tls.crt"
          volume:
            name: plex-certs
            mountPath: /etc/plex-certs
    affinity:
      podAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
        - labelSelector:
            matchExpressions:
            - key: app
              operator: In
              values:
              - nfs-server
          topologyKey: "kubernetes.io/hostname"
  valueFileSecrets:
  - name: "plex-helm-values"
