---
apiVersion: v1
kind: Service
metadata:
  name: envoy
  namespace: projectcontour
  labels:
    app: envoy
spec:
  selector:
    app: envoy
  type: ClusterIP
  clusterIP: None
  ports:
  - name: prometheus-metrics
    port: 8002
    targetPort: 8002
    protocol: TCP
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: envoy-monitor
  namespace: monitoring
  labels:
    release: kube-prometheus-stack
spec:
  selector:
    matchLabels:
      app: envoy
  endpoints:
  - port: prometheus-metrics
