---
apiVersion: v1
kind: Service
metadata:
  name: envoy-metrics
  namespace: projectcontour
  labels:
    app: envoy
spec:
  ports:
  - name: prometheus-metrics
    port: 8002
    targetPort: 8002
    protocol: TCP
  selector:
    app: envoy
  type: ClusterIP
