---
apiVersion: v1
kind: Service
metadata:
  name: envoy
  namespace: projectcontour
  lables:
    discover: envoy-metrics
spec:
  ports:
  - name: prometheus-metrics
    port: 8002
    targetPort: 8002
    protocol: TCP
  selector:
    discover: envoy-metrics
  type: ClusterIP
