---
apiVersion: v1
kind: Service
metadata:
  name: contour
  namespace: projectcontour
  labels:
    release: kube-prometheus-stack
spec:
  ports:
  - port: 8001
    name: xds
    protocol: TCP
    targetPort: 8001
  - port: 8000
    name: debug
    protocol: TCP
    targetPort: 8000
  selector:
    app: contour
  type: ClusterIP
