apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  namespace: monitoring
  name: prometheus-contour
  labels:
    release: kube-prometheus-stack
spec:
  namespaceSelector:
    matchNames:
    - projectcontour
  endpoints:
  - path: /metrics
    port: debug
    scheme: http
  selector:
    matchLabels:
      poop: colon
