apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  namespace: monitoring
  name: kube-prometheus-stack-contour
  labels:
    app: contour
spec:
  namespaceSelector:
    matchNames:
    - projectcontour
  jobLabel: jobLabel
  endpoints:
  - port: debug
  selector:
    matchLabels:
      service: contour
