apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  namespace: monitoring
  name: prometheus-envoy
  labels:
    release: kube-prometheus-stack
spec:
  namespaceSelector:
    matchNames:
    - projectcontour
  endpoints:
  - path: /stats/prometheus
    port: prometheus-metrics
    scheme: http
  selector:
    matchLabels:
      app: envoy
