apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  namespace: monitoring
  name: prometheus-envoy
  labels:
    release: kube-prometheus-stack
spec:
  namespaceSelector:
    matchNames:
    - projectcontour
  podMetricsEndpoints:
  - path: /stats/prometheus
    port: "8002"
    scheme: http
  selector:
    matchLabels:
      app: envoy
