---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: contour
  namespace: projectcontour
spec:
  releaseName: contour
  helmVersion: v3
  rollback:
    enable: true
  chart:
    repository: https://charts.bitnami.com/bitnami
    name: contour
    version: 2.0.0
