---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: vault-secrets-operator
  namespace: kube-system
  annotations:
    fluxcd.io/automated: "true"
    fluxcd.io/tag.chart-image: semver:~1.7
spec:
  releaseName: vault-secrets-operator
  rollback:
    enable: true
  chart:
    repository: https://ricoberger.github.io/helm-charts
    name: vault-secrets-operator
    version: 1.7.1
  valuesFrom:
  - externalSourceRef:
      url: https://raw.githubusercontent.com/nctiggy/home-gitops/master/kube-system/vault-secrets-operator/vault-secrets-operator-values.yaml
createCRD: true
