---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: prometheus
  namespace: monitoring
  annotations:
    fluxcd.io/automated: "false"
    fluxcd.io/tag.chart-image: 'regexp:^(1\.[0-9]+\.[0-9]+)$'
spec:
  releaseName: kube-prometheus-stack
  rollback:
    enable: true
  chart:
    repository: https://prometheus-community.github.io/helm-charts
    name: kube-prometheus-stack
    version: 10.1.2
  values:
    namespaceOverride: monitoring
    alertmanager:
      enabled: true
      ingress:
        enabled: true
  valueFileSecrets:
  - name: "prometheus-helm-values"
