---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: flux
  namespace: flux
  annotations:
    fluxcd.io/automated: "true"
    filter.fluxcd.io/chart-image: semver:~1.20.
spec:
  releaseName: flux
  helmVersion: v3
  chart:
    repository: https://charts.fluxcd.io/
    name: flux
    version: 1.4.1
  values:
    image:
      repository: docker.io/fluxcd/flux
      tag: 1.22.1
      pullPolicy: IfNotPresent
    git:
      url: "git@github.com:nctiggy/home-gitops"
    additionalArgs:
    - --connect=ws://fluxcloud
    syncGarbageCollection:
      enabled: true
    dashboards:
      enabled: true
