image:
  repository: docker.io/fluxcd/flux
  tag: 1.20.2
  pullPolicy: IfNotPresent
git:
  url: "git@github.com:nctiggy/home-gitops"
additionalArgs:
- --connect=ws://fluxcloud
syncGarbageCollection:
  enabled: true
dashboards:
  enabled: true
