---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: botkube
  namespace: monitoring
  annotations:
    fluxcd.io/automated: "true"
spec:
  releaseName: botkube
  rollback:
    enable: true
  chart:
    repository: https://infracloudio.github.io/charts
    name: botkube
    version: v0.10.0
  valuesFrom:
  - externalSourceRef:
      url: https://raw.githubusercontent.com/nctiggy/home-gitops/master/monitoring/botkube/botkube-values.yaml
  valueFileSecrets:
  - name: "botkube-secret"
