---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mc-data-survival
  namespace: work
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 64Gi
  storageClassName: vxflexos
  volumeMode: Filesystem
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mc-stage
  namespace: work
spec:
  selector:
    matchLabels:
      app: mc-stage
  template:
    metadata:
      labels:
        app: mc-stage
    spec:
      containers:
      - image: busybox
        name: mc-stage
        imagePullPolicy: Always
        volumeMounts:
        - name: mc-data-survival
          mountPath: /data
      volumes:
      - name: mc-data-survival
        persistentVolumeClaim:
          claimName: mc-data-survival
