---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: calibre
  namespace: media
  annotations:
    fluxcd.io/automated: "false"
    filter.fluxcd.io/chart-image: glob:v21.*
spec:
  releaseName: calibre
  helmVersion: v3
  rollback:
    enable: true
  chart:
    repository: https://k8s-at-home.com/charts/
    name: calibre
    version: 3.3.0
  values:
    timezone: "America/Los_Angeles"
    persistence:
      config:
        enabled: true
        existingClaim: calibre
        skipuninstall: true
  valueFileSecrets:
  - name: "calibre-helm-values"
