---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: calibre
  namespace: media
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 256Gi
  storageClassName: vxflexos
  volumeMode: Filesystem
