apiVersion: apps/v1
kind: Deployment
metadata:
  name: terminal
  namespace: media
  labels:
    app: terminal
spec:
  replicas: 1
  strategy:
    type: Recreate
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: terminal
  template:
    metadata:
      labels:
        app: terminal
    spec:
      containers:
      - name: wetty
        image: butlerx/wetty
        ports:
        - containerPort: 3000
          protocol: TCP
        livenessProbe:
          tcpSocket:
            port: 3000
          initialDelaySeconds: 30
          failureThreshold: 5
          timeoutSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: terminal
  namespace: media
spec:
  selector:
    app: terminal
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
  type: ClusterIP
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: terminal-dashboard-tls
  namespace: media
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`terminal.web.bluehairfreak.com`)
      kind: Rule
      services:
        - name: terminal
          port: 3000
  tls:
    certResolver: myresolver
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: terminal-dashboard
  namespace: media
spec:
  entryPoints:
    - web
  routes:
    - match: Host(`terminal.web.bluehairfreak.com`)
      kind: Rule
      services:
        - name: terminal
          port: 3000
