apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: esphome-config
  namespace: iot
  annotations:
    helm.sh/resource-policy: keep
    meta.helm.sh/release-name: esphome
    meta.helm.sh/release-namespace: iot
  labels:
    app.kubernetes.io/instance: esphome
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: esphome
    helm.sh/chart: esphome-1.0.1
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 56Gi
  storageClassName: vxflexos
