---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: esphome
  namespace: iot
  annotations:
    fluxcd.io/automated: "true"
    filter.fluxcd.io/chart-image: semver:1.14
spec:
  releaseName: esphome
  helmVersion: v3
  rollback:
    enable: true
  chart:
    repository: https://billimek.com/billimek-charts/
    name: esphome
    version: 1.0.0
  values:
    image:
      repository: esphome/esphome
      tag: 1.14.5
    hostNetwork: true
    persistence:
      enabled: true
      #      existingClaim: esphome-config
