---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: telegraf
  namespace: monitoring
  annotations:
    fluxcd.io/automated: "false"
    fluxcd.io/tag.chart-image: 'regexp:^(1\.[0-9]+\.[0-9]+)$'
spec:
  releaseName: telegraf
  rollback:
    enable: true
  chart:
    repository: https://helm.influxdata.com/
    name: telegraf
    version: 1.7.23
  values:
    config:
      outputs:
      - influxdb:
          urls:
          - "http://influxdb.monitoring.svc:8086"
          database: "telegraf"
      inputs:
      - snmp:
          agents: ["192.168.0.98"]
          timeout: "5s"
          version: 2
          community: "public"
          field:
            name: "hostname"
            oid: "SNMPv2-MIB::sysName.0"
            is_tag: true
