---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: cert-manager
  namespace: cert-manager
  annotations:
    fluxcd.io/automated: "false"
    filter.fluxcd.io/chart-image: semver:3.0
spec:
  releaseName: cert-manager
  helmVersion: v3
  rollback:
    enable: true
  chart:
    repository: https://charts.jetstack.io
    name: cert-manager
    version: 1.4.0
  values:
    image:
      repository: quay.io/jetstack/cert-manager-controller
      tag: "v1.4.0"
    installCRDs: true
